import BerryEsseen.FiniteBezout
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected
import Mathlib.Data.ZMod.Basic

/-! The manuscript's Cayley-graph proof of the coefficient bound 4000.
Unbounded Bezout gives connectivity only. Loop erasure produces a simple
path with at most m vertices and fewer than m edges; its signed edges
provide the small coefficients used in the spectral-gap argument. -/
noncomputable section
open Set Function
namespace BerryEsseen

def manuscriptCayleyGraph (D : Finset ℕ) (m : ℕ) : SimpleGraph (ZMod m) where
  Adj x y := x ≠ y ∧ ∃ d ∈ D, ∃ e : ℤ, |e| = 1 ∧ y = x + (e : ZMod m) * (d : ZMod m)
  symm := by
    rintro x y ⟨hne, d, hd, e, he, rfl⟩
    refine ⟨hne.symm, d, hd, -e, by simpa only [abs_neg] using he, ?_⟩
    push_cast
    ring
  loopless := ⟨fun x h => h.1 rfl⟩

theorem manuscript_cayley_step (D : Finset ℕ) (m d : ℕ) (hd : d ∈ D)
    (e : ℤ) (he : |e| = 1) (x : ZMod m) :
    (manuscriptCayleyGraph D m).Reachable x (x + (e : ZMod m) * (d : ZMod m)) := by
  by_cases hh : x = x + (e : ZMod m) * (d : ZMod m)
  · simpa only [← hh] using (SimpleGraph.Reachable.rfl (G := manuscriptCayleyGraph D m) (u := x))
  · exact SimpleGraph.Adj.reachable ⟨hh, d, hd, e, he, rfl⟩

theorem manuscript_cayley_repeated_step (D : Finset ℕ) (m d : ℕ) (hd : d ∈ D)
    (e : ℤ) (he : |e| = 1) (k : ℕ) (x : ZMod m) :
    (manuscriptCayleyGraph D m).Reachable x (x + (k : ZMod m) * ((e : ZMod m) * d)) := by
  induction k with
  | zero => simpa using (SimpleGraph.Reachable.rfl (G := manuscriptCayleyGraph D m) (u := x))
  | succ k ih =>
    have hh := ih.trans (manuscript_cayley_step D m d hd e he
      (x + (k : ZMod m) * ((e : ZMod m) * d)))
    convert hh using 1 <;> (push_cast; ring)

theorem manuscript_cayley_integer_step (D : Finset ℕ) (m d : ℕ) (hd : d ∈ D)
    (c : ℤ) (x : ZMod m) :
    (manuscriptCayleyGraph D m).Reachable x (x + (c : ZMod m) * d) := by
  cases c with
  | ofNat k =>
    simpa using manuscript_cayley_repeated_step D m d hd 1 (by norm_num) k x
  | negSucc k =>
    convert manuscript_cayley_repeated_step D m d hd (-1) (by norm_num) (k + 1) x using 1 <;>
      (push_cast; ring)

theorem manuscript_cayley_sum_reachable (D : Finset ℕ) (m : ℕ) (c : ℕ → ℤ)
    (F : Finset ℕ) (hFD : F ⊆ D) (x : ZMod m) :
    (manuscriptCayleyGraph D m).Reachable x
      (x + ∑ d ∈ F, (c d : ZMod m) * (d : ZMod m)) := by
  classical
  revert hFD x
  induction F using Finset.induction_on with
  | empty => intro hFD x; simpa using (SimpleGraph.Reachable.rfl (G := manuscriptCayleyGraph D m) (u := x))
  | @insert d F hd ih =>
    intro hFD x
    have hstep := manuscript_cayley_integer_step D m d (hFD (Finset.mem_insert_self _ _)) (c d) x
    have htail := ih (fun a ha => hFD (Finset.mem_insert_of_mem ha))
      (x + (c d : ZMod m) * (d : ZMod m))
    have hh := hstep.trans htail
    simpa only [Finset.sum_insert hd, add_assoc] using hh

/-- The Cayley graph generated by the residues ±d is connected when
the integer generators have gcd one, exactly as used in the manuscript. -/
theorem manuscript_cayley_connected (D : Finset ℕ) (m : ℕ)
    (hgcd : D.gcd id = 1) : (manuscriptCayleyGraph D m).Connected := by
  apply (SimpleGraph.connected_iff_exists_forall_reachable (G := manuscriptCayleyGraph D m)).2
  refine ⟨0, fun y => ?_⟩
  obtain ⟨a, ha⟩ := ZMod.intCast_surjective y
  obtain ⟨c, hc⟩ := finite_nat_gcd_bezout D
  rw [hgcd, Nat.cast_one] at hc
  have hac : (∑ d ∈ D, (a * c d) * (d : ℤ)) = a := by
    calc
      _ = a * ∑ d ∈ D, c d * (d : ℤ) := by rw [Finset.mul_sum]; congr 1; ext d; ring
      _ = a := by rw [hc, mul_one]
  have hcZ : (∑ d ∈ D, ((a * c d : ℤ) : ZMod m) * (d : ZMod m)) = y := by
    have hh := congrArg (fun b : ℤ => (b : ZMod m)) hac
    simpa only [Int.cast_sum, Int.cast_mul, Int.cast_natCast, ha] using hh
  simpa only [hcZ, zero_add] using
    manuscript_cayley_sum_reachable D m (fun d => a * c d) D (fun _ h => h) 0

/-- Gcd one gives a walk from zero to one in the actual residue Cayley graph. -/
theorem manuscript_cayley_zero_one_reachable (D : Finset ℕ) (m : ℕ)
    (hgcd : D.gcd id = 1) : (manuscriptCayleyGraph D m).Reachable 0 1 := by
  obtain ⟨c, hc⟩ := finite_nat_gcd_bezout D
  rw [hgcd, Nat.cast_one] at hc
  have hcZ : (∑ d ∈ D, (c d : ZMod m) * (d : ZMod m)) = 1 := by
    have hh := congrArg (fun a : ℤ => (a : ZMod m)) hc
    simpa only [Int.cast_sum, Int.cast_mul, Int.cast_natCast, Int.cast_one] using hh
  simpa only [hcZ, zero_add] using manuscript_cayley_sum_reachable D m c D (fun _ h => h) 0

/-- Read the signed edges of any walk. Their collected coefficients have
total absolute value at most the number of edges. -/
theorem manuscript_cayley_walk_coefficients (D : Finset ℕ) (m : ℕ)
    {x y : ZMod m} (p : (manuscriptCayleyGraph D m).Walk x y) :
    ∃ c : ℕ → ℤ,
      ((∑ d ∈ D, c d * (d : ℤ) : ℤ) : ZMod m) = y - x ∧
      (∑ d ∈ D, |c d|) ≤ (p.length : ℤ) := by
  classical
  induction p with
  | nil => exact ⟨fun _ => 0, by simp, by simp⟩
  | @cons x z y hxz p ih =>
    obtain ⟨c, hc, hcl⟩ := ih
    obtain ⟨hne, d, hd, e, he, hz⟩ := hxz
    let b : ℕ → ℤ := fun k => c k + if k = d then e else 0
    have hb : (∑ k ∈ D, b k * (k : ℤ)) = (∑ k ∈ D, c k * (k : ℤ)) + e * d := by
      simp only [b, add_mul, Finset.sum_add_distrib]
      congr 1
      simp only [ite_mul, zero_mul]
      simp [hd]
    refine ⟨b, ?_, ?_⟩
    · rw [hb]
      push_cast at hc ⊢
      rw [hc, hz]
      ring
    · have hsum : (∑ k ∈ D, |b k|) ≤ (∑ k ∈ D, |c k|) + 1 := by
        calc
          _ ≤ ∑ k ∈ D, (|c k| + |if k = d then e else 0|) := by
            apply Finset.sum_le_sum
            intro k hk
            exact abs_add_le _ _
          _ = _ := by
            rw [Finset.sum_add_distrib]
            simp_rw [apply_ite abs, he, abs_zero]
            simp [hd]
      simp only [SimpleGraph.Walk.length_cons, Nat.cast_add, Nat.cast_one]
      linarith

end BerryEsseen
